services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres

  backend:
    depends_on:
      - db
    image: bulbawarrior/internship_backend:v1.0.1
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db
      FRONTEND_URL: http://frontend:3000

    
  frontend:
    depends_on:
      - backend
    image: bulbawarrior/internship_frontend:0311752f427facce9326004facd29ed1e0807a35
    environment:
      REACT_APP_BASE_URL: http://backend:5000
    ports:
      - 3000:3000
