apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXMzMjExMjM=
  url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzMzIxMTIzQGRiLXNlcnZpY2U=
