name: ci
on: pull_request

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install npm dependecies
      run: npm install
      
    - name: Run linter
      run: npm run lint
      
  Build_image:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: bulbawarrior/internship_frontend:${{ github.sha }}
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
