name: local-release
on: 
  workflow_dispatch:
    inputs:
      service_image_name:
        description: the service image to be updated
        required: true
        
      registry_url:
        required: true
        
      tag:
        description: version tag of the image
        required: true


jobs:
  Update:
    env:
      IMAGE: ${{ github.event.inputs.service_image_name }}
      REGISTRY: ${{ github.event.inputs.registry_url }}
      TAG: ${{ github.event.inputs.tag }}
      
    runs-on: ubuntu-latest
    name: Bump image tag
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update image tag in helm charts
        uses: jacobtomlinson/gha-find-replace@0.1.4
        with:
          include: 'values.yaml'
          find: '  full: .*${{ env.IMAGE }}.*'
          replace: '  full: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}'
          
      - name: Push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Releasing $IMAGE:$TAG" -a
          git push
      
